// ⚠⚠⚠ Code generated by go generate; DO NOT EDIT ⚠⚠⚠
package main

const (
	usageText = "# Using the ContainerSSH agent\n" + 
		"\n" + 
		"This is the agent meant to be installed in the containers run by\n" + 
		"ContainerSSH. While images work without this agent, several features\n" + 
		"may not be available depending on what the container engine supports.\n" + 
		"\n" + 
		"## Usage\n" + 
		"\n" + 
		"    ./agent MODE [OPTIONS] \n" + 
		"\n" + 
		"Currently, the agent has the following modes:\n" + 
		"\n" + 
		"console\n" + 
		"    This mode will take care of console-related activities.\n" + 
		"\n" + 
		"signal\n" + 
		"    This mode will send a signal to a process.\n" + 
		"\n" + 
		"wait-signal\n" + 
		"    Waits for a specific signal or signals before it exits.\n" + 
		"\n" + 
		"write-file\n" + 
		"    Write standard input into the given file\n" + 
		"\n" + 
		"license\n" + 
		"    This mode will print the license of the agent and exit.\n" + 
		"\n" + 
		"----------------------------------------------------------------------------\n" + 
		"\n" + 
		"## Console mode\n" + 
		"\n" + 
		"The console mode takes care of console-related settings that are not\n" + 
		"supported by the container backend. The console mode has the following\n" + 
		"required argument:\n" + 
		"\n" + 
		"    ./agent MODE [OPTIONS] -- PROGRAM\n" + 
		"\n" + 
		"The program will be launched with execve and replace the agent\n" + 
		"completely. (The agent will not be running once the program is launched.)\n" + 
		"This makes the agent safe to run even when you need the program to be run\n" + 
		"as PID 1.\n" + 
		"\n" + 
		"### Setting environment variables\n" + 
		"\n" + 
		"The console mode accepts environment variables because some container\n" + 
		"backends, such as Kubernetes on exec, do not support setting environment\n" + 
		"variables.\n" + 
		"\n" + 
		"Environment variables can be set using the following argument form:\n" + 
		"\n" + 
		"    --env NAME=VALUE\n" + 
		"\n" + 
		"## Waiting\n" + 
		"\n" + 
		"Kubernetes does not wait for a console to be attached, therefore a first\n" + 
		"line of a shell or equivalent will be lost. Therefore, the agent has a\n" + 
		"--wait flag.\n" + 
		"\n" + 
		"The --wait flag will not launch the desired program until a byte with\n" + 
		"the value of \\0 or a newline (\\n) is received on stdin. This byte will\n" + 
		"not be passed to the program and if any other byte is received the agent\n" + 
		"will exit to prevent data stream corruption.\n" + 
		"\n" + 
		"## Writing files\n" + 
		"\n" + 
		"The backend APIs do not support adding custom files on the fly in containers.\n" + 
		"So the write-file mode was created. The mode takes just one argument, the\n" + 
		"name and path of the file to write. The contents of the file will be read from\n" + 
		"standard input\n" + 
		"\n" + 
		"## Reporting PID\n" + 
		"\n" + 
		"Since most container implementations don't report the PID of the process\n" + 
		"inside the container in the exec method the --pid flag will report\n" + 
		"the PID of the current program over stdout in the first 4 bytes as a \n" + 
		"little-endian uint32.\n" + 
		"\n" + 
		"## Return codes\n" + 
		"\n" + 
		"This program will exit with one of the following exit codes:\n" + 
		"\n" + 
		"1\n" + 
		"    General configuration error. See stderr for details.\n" + 
		"\n" + 
		"2\n" + 
		"    Could not read from stdin with --wait.\n" + 
		"\n" + 
		"3\n" + 
		"    Could not write PID to stdout with --pid.\n" + 
		"\n" + 
		"127\n" + 
		"    Could not execute desired program.\n" + 
		"\n" + 
		"----------------------------------------------------------------------------\n" + 
		"\n" + 
		"## Signal mode\n" + 
		"\n" + 
		"The signal mode is useful for forwarding signals to processes that are\n" + 
		"already running.\n" + 
		"\n" + 
		"The signal mode has the following syntax:\n" + 
		"\n" + 
		"    ./agent signal --pid 1234 --signal ABRT\n" + 
		"\n" + 
		"The signal names are, as per RFC 4254 Section 6.9:\n" + 
		"\n" + 
		"- ABRT\n" + 
		"- ALRM\n" + 
		"- FPE\n" + 
		"- HUP\n" + 
		"- ILL\n" + 
		"- INT\n" + 
		"- KILL\n" + 
		"- PIPE\n" + 
		"- QUIT\n" + 
		"- SEGV\n" + 
		"- TERM\n" + 
		"- USR1\n" + 
		"- USR2\n" + 
		"\n" + 
		"Note: USR1 and USR2 are not supported on Windows.\n" + 
		"\n" + 
		"This mode has the following exit codes:\n" + 
		"\n" + 
		"0\n" + 
		"    Signal successfully sent.\n" + 
		"\n" + 
		"1\n" + 
		"    General configuration error. See stderr for details.\n" + 
		"\n" + 
		"2\n" + 
		"    The specified process was not found. See stderr for details.\n" + 
		"\n" + 
		"3\n" + 
		"    Failed to send signal to process. See stderr for details.\n" + 
		"\n" + 
		"----------------------------------------------------------------------------\n" + 
		"\n" + 
		"## Waiting for a signal\n" + 
		"\n" + 
		"In this mode the agent waits for the specified signal or signals before exiting. This is useful when running the agent as the init process in a container.\n" + 
		"\n" + 
		"It can be run as follows:\n" + 
		"\n" + 
		"    ./agent wait-signal --signal ABRT --message \"Hello world!\"\n" + 
		"\n" + 
		"The --signal option can be repeated and the --message option is optional.\n" + 
		"\n" + 
		"The following signals are supported:\n" + 
		"\n" + 
		"- ABRT\n" + 
		"- ALRM\n" + 
		"- FPE\n" + 
		"- HUP\n" + 
		"- ILL\n" + 
		"- INT\n" + 
		"- KILL\n" + 
		"- PIPE\n" + 
		"- QUIT\n" + 
		"- SEGV\n" + 
		"- TERM\n" + 
		"- USR1\n" + 
		"- USR2\n" + 
		"\n" + 
		"Note: USR1 and USR2 are not supported on Windows.\n" + 
		"\n"
	usageTextColored = "\033[1m\033[97m# Using the ContainerSSH agent\033[0m\n" + 
		"\n" + 
		"This is the agent meant to be installed in the containers run by\n" + 
		"ContainerSSH. While images work without this agent, several features\n" + 
		"may not be available depending on what the container engine supports.\n" + 
		"\n" + 
		"\033[1m\033[97m## Usage\033[0m\n" + 
		"\n" + 
		"\033[97m    ./agent MODE [OPTIONS] \033[0m\n" + 
		"\n" + 
		"Currently, the agent has the following modes:\n" + 
		"\n" + 
		"\033[97mconsole\033[0m\n" + 
		"    This mode will take care of console-related activities.\n" + 
		"\n" + 
		"\033[97msignal\033[0m\n" + 
		"    This mode will send a signal to a process.\n" + 
		"\n" + 
		"\033[97mwait-signal\033[0m\n" + 
		"    Waits for a specific signal or signals before it exits.\n" + 
		"\n" + 
		"\033[97mwrite-file\033[0m\n" + 
		"    Write standard input into the given file\n" + 
		"\n" + 
		"\033[97mlicense\033[0m\n" + 
		"    This mode will print the license of the agent and exit.\n" + 
		"\n" + 
		"----------------------------------------------------------------------------\n" + 
		"\n" + 
		"\033[1m\033[97m## Console mode\033[0m\n" + 
		"\n" + 
		"The console mode takes care of console-related settings that are not\n" + 
		"supported by the container backend. The console mode has the following\n" + 
		"required argument:\n" + 
		"\n" + 
		"\033[97m    ./agent MODE [OPTIONS] -- PROGRAM\033[0m\n" + 
		"\n" + 
		"The program will be launched with \033[97mexecve\033[0m and replace the agent\n" + 
		"completely. (The agent will not be running once the program is launched.)\n" + 
		"This makes the agent safe to run even when you need the program to be run\n" + 
		"as PID 1.\n" + 
		"\n" + 
		"\033[1m\033[97m### Setting environment variables\033[0m\n" + 
		"\n" + 
		"The console mode accepts environment variables because some container\n" + 
		"backends, such as Kubernetes on \033[97mexec\033[0m, do not support setting environment\n" + 
		"variables.\n" + 
		"\n" + 
		"Environment variables can be set using the following argument form:\n" + 
		"\n" + 
		"\033[97m    --env NAME=VALUE\033[0m\n" + 
		"\n" + 
		"\033[1m\033[97m## Waiting\033[0m\n" + 
		"\n" + 
		"Kubernetes does not wait for a console to be attached, therefore a first\n" + 
		"line of a shell or equivalent will be lost. Therefore, the agent has a\n" + 
		"\033[97m--wait\033[0m flag.\n" + 
		"\n" + 
		"The \033[97m--wait\033[0m flag will not launch the desired program until a byte with\n" + 
		"the value of \033[97m\\0\033[0m or a newline (\033[97m\\n\033[0m) is received on \033[97mstdin\033[0m. This byte will\n" + 
		"not be passed to the program and if any other byte is received the agent\n" + 
		"will exit to prevent data stream corruption.\n" + 
		"\n" + 
		"\033[1m\033[97m## Writing files\033[0m\n" + 
		"\n" + 
		"The backend APIs do not support adding custom files on the fly in containers.\n" + 
		"So the \033[97mwrite-file\033[0m mode was created. The mode takes just one argument, the\n" + 
		"name and path of the file to write. The contents of the file will be read from\n" + 
		"standard input\n" + 
		"\n" + 
		"\033[1m\033[97m## Reporting PID\033[0m\n" + 
		"\n" + 
		"Since most container implementations don't report the PID of the process\n" + 
		"inside the container in the \033[97mexec\033[0m method the \033[97m--pid\033[0m flag will report\n" + 
		"the PID of the current program over stdout in the first 4 bytes as a \n" + 
		"little-endian uint32.\n" + 
		"\n" + 
		"\033[1m\033[97m## Return codes\033[0m\n" + 
		"\n" + 
		"This program will exit with one of the following exit codes:\n" + 
		"\n" + 
		"\033[97m1\033[0m\n" + 
		"    General configuration error. See \033[97mstderr\033[0m for details.\n" + 
		"\n" + 
		"\033[97m2\033[0m\n" + 
		"    Could not read from \033[97mstdin\033[0m with \033[97m--wait\033[0m.\n" + 
		"\n" + 
		"\033[97m3\033[0m\n" + 
		"    Could not write PID to \033[97mstdout\033[0m with \033[97m--pid\033[0m.\n" + 
		"\n" + 
		"\033[97m127\033[0m\n" + 
		"    Could not execute desired program.\n" + 
		"\n" + 
		"----------------------------------------------------------------------------\n" + 
		"\n" + 
		"\033[1m\033[97m## Signal mode\033[0m\n" + 
		"\n" + 
		"The signal mode is useful for forwarding signals to processes that are\n" + 
		"already running.\n" + 
		"\n" + 
		"The signal mode has the following syntax:\n" + 
		"\n" + 
		"\033[97m    ./agent signal --pid 1234 --signal ABRT\033[0m\n" + 
		"\n" + 
		"The signal names are, as per RFC 4254 Section 6.9:\n" + 
		"\n" + 
		"- \033[97mABRT\033[0m\n" + 
		"- \033[97mALRM\033[0m\n" + 
		"- \033[97mFPE\033[0m\n" + 
		"- \033[97mHUP\033[0m\n" + 
		"- \033[97mILL\033[0m\n" + 
		"- \033[97mINT\033[0m\n" + 
		"- \033[97mKILL\033[0m\n" + 
		"- \033[97mPIPE\033[0m\n" + 
		"- \033[97mQUIT\033[0m\n" + 
		"- \033[97mSEGV\033[0m\n" + 
		"- \033[97mTERM\033[0m\n" + 
		"- \033[97mUSR1\033[0m\n" + 
		"- \033[97mUSR2\033[0m\n" + 
		"\n" + 
		"\033[1mNote:\033[0m \033[97mUSR1\033[0m and \033[97mUSR2\033[0m are not supported on Windows.\n" + 
		"\n" + 
		"This mode has the following exit codes:\n" + 
		"\n" + 
		"\033[97m0\033[0m\n" + 
		"    Signal successfully sent.\n" + 
		"\n" + 
		"\033[97m1\033[0m\n" + 
		"    General configuration error. See \033[97mstderr\033[0m for details.\n" + 
		"\n" + 
		"\033[97m2\033[0m\n" + 
		"    The specified process was not found. See \033[97mstderr\033[0m for details.\n" + 
		"\n" + 
		"\033[97m3\033[0m\n" + 
		"    Failed to send signal to process. See \033[97mstderr\033[0m for details.\n" + 
		"\n" + 
		"----------------------------------------------------------------------------\n" + 
		"\n" + 
		"\033[1m\033[97m## Waiting for a signal\033[0m\n" + 
		"\n" + 
		"In this mode the agent waits for the specified signal or signals before exiting. This is useful when running the agent as the init process in a container.\n" + 
		"\n" + 
		"It can be run as follows:\n" + 
		"\n" + 
		"\033[97m    ./agent wait-signal --signal ABRT --message \"Hello world!\"\033[0m\n" + 
		"\n" + 
		"The \033[97m--signal\033[0m option can be repeated and the \033[97m--message\033[0m option is optional.\n" + 
		"\n" + 
		"The following signals are supported:\n" + 
		"\n" + 
		"- \033[97mABRT\033[0m\n" + 
		"- \033[97mALRM\033[0m\n" + 
		"- \033[97mFPE\033[0m\n" + 
		"- \033[97mHUP\033[0m\n" + 
		"- \033[97mILL\033[0m\n" + 
		"- \033[97mINT\033[0m\n" + 
		"- \033[97mKILL\033[0m\n" + 
		"- \033[97mPIPE\033[0m\n" + 
		"- \033[97mQUIT\033[0m\n" + 
		"- \033[97mSEGV\033[0m\n" + 
		"- \033[97mTERM\033[0m\n" + 
		"- \033[97mUSR1\033[0m\n" + 
		"- \033[97mUSR2\033[0m\n" + 
		"\n" + 
		"\033[1mNote:\033[0m \033[97mUSR1\033[0m and \033[97mUSR2\033[0m are not supported on Windows.\n" + 
		"\n"

)
